import { ProjectData } from './types';

export const initialProject: ProjectData = {
  id: 'prd-solar-rooftop-01',
  projectName: 'โครงการติดตั้งระบบผลิตไฟฟ้าจากพลังงานแสงอาทิตย์แบบติดตั้งบนหลังคา (Solar Rooftop) ภายในพื้นที่ของกรมประชาสัมพันธ์',
  customerName: 'กรมประชาสัมพันธ์',
  projectType: 'Solar Rooftop',
  contractCapacityTotal: 3510.84,
  actualCapacityTotal: 2095.36,
  contractNumber: 'เลขที่ ฝรด.กร.2 (SA) 014/2566 ลงวันที่ 22 สิงหาคม 2566',
  serviceDiscountPercent: 25,
  servicePeriodYears: 25,
  contractValue: 325395321.32,
  targetCO2ReductionFactor: 0.477,
  meaContact: {
    department: 'ฝ่ายธุรกิจบริการคุณภาพไฟฟ้า',
    contactName: 'นายศักดิ์ดา เด่นดวง',
    position: 'วิศวกรไฟฟ้าอาวุโส',
    phone: '02 256 3333',
    email: 'mea.energy@mea.or.th',
  },
  customerContact: {
    contactName: 'นางสาววิภาวี รักษ์ไทย',
    position: 'ผู้อำนวยการกองประสานงานโครงการ',
    phone: '02 618 2300',
    email: 'prd.contact@prd.go.th',
  },
  updatedDate: '2026-05-22T14:30:00',
  locations: [
    {
      id: 'loc-1',
      name: 'กรุงเทพมหานคร (อารีย์)',
      subAgency: 'สถานีโทรทัศน์แห่งประเทศไทย (อาคาร NBT)',
      capacityKWp: 713.00,
      actualCapacityKWp: 713.00,
      province: 'กรุงเทพมหานคร',
      region: 'กรุงเทพมหานคร',
      status: 'ติดตั้งแล้ว',
    },
    {
      id: 'loc-2',
      name: 'กรุงเทพมหานคร (วิทยุ)',
      subAgency: 'สถานีวิทยุกระจายเสียงแห่งประเทศไทย',
      capacityKWp: 500.28,
      actualCapacityKWp: 500.28,
      province: 'กรุงเทพมหานคร',
      region: 'กรุงเทพมหานคร',
      status: 'ติดตั้งแล้ว',
    },
    {
      id: 'loc-3',
      name: 'กรุงเทพมหานคร (สำนักข่าว)',
      subAgency: 'สำนักข่าว กรมประชาสัมพันธ์',
      capacityKWp: 679.80,
      actualCapacityKWp: 679.80,
      province: 'กรุงเทพมหานคร',
      region: 'กรุงเทพมหานคร',
      status: 'ติดตั้งแล้ว',
    },
    {
      id: 'loc-4',
      name: 'เชียงใหม่',
      subAgency: 'กรมประชาสัมพันธ์ เขต 3',
      capacityKWp: 101.14,
      actualCapacityKWp: 101.14,
      province: 'เชียงใหม่',
      region: 'ภาคเหนือ',
      status: 'ติดตั้งแล้ว',
    },
    {
      id: 'loc-5',
      name: 'พิษณุโลก',
      subAgency: 'กรมประชาสัมพันธ์ เขต 4',
      capacityKWp: 101.14,
      actualCapacityKWp: 101.14,
      province: 'พิษณุโลก',
      region: 'ภาคเหนือ',
      status: 'ติดตั้งแล้ว',
    },
    {
      id: 'loc-6',
      name: 'ลำปาง',
      subAgency: 'สวท. ลำปาง ภาคเหนือ',
      capacityKWp: 100.00,
      actualCapacityKWp: 0,
      province: 'ลำปาง',
      region: 'ภาคเหนือ',
      status: 'อยู่ระหว่างดำเนินการ',
    },
    {
      id: 'loc-7',
      name: 'ขอนแก่น',
      subAgency: 'กรมประชาสัมพันธ์ เขต 1',
      capacityKWp: 120.12,
      actualCapacityKWp: 0,
      province: 'ขอนแก่น',
      region: 'ภาคตะวันออกเฉียงเหนือ',
      status: 'อยู่ระหว่างดำเนินการ',
    },
    {
      id: 'loc-8',
      name: 'อุบลราชธานี',
      subAgency: 'กรมประชาสัมพันธ์ เขต 2',
      capacityKWp: 100.32,
      actualCapacityKWp: 0,
      province: 'อุบลราชธานี',
      region: 'ภาคตะวันออกเฉียงเหนือ',
      status: 'อยู่ระหว่างดำเนินการ',
    },
    {
      id: 'loc-9',
      name: 'จันทบุรี',
      subAgency: 'กรมประชาสัมพันธ์ เขต 7',
      capacityKWp: 135.18,
      actualCapacityKWp: 0,
      province: 'จันทบุรี',
      region: 'ภาคตะวันออก',
      status: 'อยู่ระหว่างดำเนินการ',
    },
    {
      id: 'loc-10',
      name: 'กาญจนบุรี',
      subAgency: 'กรมประชาสัมพันธ์ เขต 8',
      capacityKWp: 120.12,
      actualCapacityKWp: 0,
      province: 'กาญจนบุรี',
      region: 'ภาคตะวันตก',
      status: 'อยู่ระหว่างดำเนินการ',
    },
    {
      id: 'loc-11',
      name: 'สุราษฎร์ธานี',
      subAgency: 'กรมประชาสัมพันธ์ เขต 5',
      capacityKWp: 32.18,
      actualCapacityKWp: 0,
      province: 'สุราษฎร์ธานี',
      region: 'ภาคใต้',
      status: 'อยู่ระหว่างดำเนินการ',
    },
    {
      id: 'loc-12',
      name: 'สงขลา',
      subAgency: 'กรมประชาสัมพันธ์ เขต 6',
      capacityKWp: 100.32,
      actualCapacityKWp: 0,
      province: 'สงขลา',
      region: 'ภาคใต้',
      status: 'อยู่ระหว่างดำเนินการ',
    },
    {
      id: 'loc-13',
      name: 'ปทุมธานี (รังสิต)',
      subAgency: 'สวท. รังสิต ปทุมธานี',
      capacityKWp: 120.12,
      actualCapacityKWp: 0,
      province: 'ปทุมธานี',
      region: 'กรุงเทพมหานคร',
      status: 'อยู่ระหว่างดำเนินการ',
    },
    {
      id: 'loc-14',
      name: 'สระบุรี',
      subAgency: 'สวท. 1000 กิโลวัตต์ (หนองแค)',
      capacityKWp: 559.08,
      actualCapacityKWp: 0,
      province: 'สระบุรี',
      region: 'ภาคกลาง',
      status: 'อยู่ระหว่างดำเนินการ',
    },
    {
      id: 'loc-15',
      name: 'ยะลา',
      subAgency: 'สวท. ยะลา',
      capacityKWp: 133.18,
      actualCapacityKWp: 0,
      province: 'ยะลา',
      region: 'ภาคใต้',
      status: 'อยู่ระหว่างดำเนินการ',
    }
  ],
};
